// Generated by gencpp from file turtlebot3_msgs/Sensor.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_SENSOR_H
#define TURTLEBOT3_MSGS_MESSAGE_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_msgs
{
template <class ContainerAllocator>
struct Sensor_
{
  typedef Sensor_<ContainerAllocator> Type;

  Sensor_()
    : psd_val(0)  {
    }
  Sensor_(const ContainerAllocator& _alloc)
    : psd_val(0)  {
  (void)_alloc;
    }



   typedef uint64_t _psd_val_type;
  _psd_val_type psd_val;




  typedef boost::shared_ptr< ::turtlebot3_msgs::Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_msgs::Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Sensor_

typedef ::turtlebot3_msgs::Sensor_<std::allocator<void> > Sensor;

typedef boost::shared_ptr< ::turtlebot3_msgs::Sensor > SensorPtr;
typedef boost::shared_ptr< ::turtlebot3_msgs::Sensor const> SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_msgs::Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot3_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'turtlebot3_msgs': ['/home/turtle1/catkin_ws/src/turtlebot3_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2abbca8a56388c84054beda9f2aeb349";
  }

  static const char* value(const ::turtlebot3_msgs::Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2abbca8a56388c84ULL;
  static const uint64_t static_value2 = 0x054beda9f2aeb349ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_msgs/Sensor";
  }

  static const char* value(const ::turtlebot3_msgs::Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 psd_val\n\
";
  }

  static const char* value(const ::turtlebot3_msgs::Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.psd_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_msgs::Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_msgs::Sensor_<ContainerAllocator>& v)
  {
    s << indent << "psd_val: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.psd_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_SENSOR_H
